services:
  - type: web
    name: upwork-scraper
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    # Add environment variables for Upwork login here (on Render dashboard or in render.yaml if public)
    # envVars:
    #   - key: UPWORK_EMAIL
    #     value: your_upwork_email@example.com
    #   - key: UPWORK_PASSWORD
    #     value: your_upwork_password
